server:
  port: 9001

spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-2i9k2eti.bj.tencentcdb.com:10036/tensquare_base?characterEncoding=utf-8
    username: root
    password: abc123456
    hikari:
      max-lifetime: 1800000
  rabbitmq:
    host: 192.168.167.130
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.167.130:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: bus-env, bus-refresh
