server:
  port: 9002
spring:
  application:
    name: tensquare-recruit #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-2i9k2eti.bj.tencentcdb.com:10036/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: abc123456
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true